Repository cortex-command-community/Cortex-Command-Community-Project-Source, pull requests merged in 2023-07, with the labels that each got.

#509 Fix bug where multiple gib particles would be offset by gib velocity
  Entities/MOSRotating.cpp
Labels: bug

#499 Make existing build workflows reusable
  .github/workflows/build-check.yml
  .github/workflows/ci.yml
  .github/workflows/master_build.yaml
  .github/workflows/meson.yml
  .github/workflows/msbuild.yml
Labels: refactor

#474 Add proper semantic version comparison to check mod compatibility
  CHANGELOG.md
  Menus/MainMenuGUI.cpp
  RTEA.vcxproj
  RTEA.vcxproj.filters
  System/Constants.h
  System/DataModule.cpp
  System/DataModule.h
  System/GameVersion.h
  System/Reader.cpp
  System/Reader.h
  System/Semver200/Semver200_comparator.cpp
  System/Semver200/Semver200_modifier.cpp
  System/Semver200/Semver200_parser.cpp
  System/Semver200/semver200.h
  System/Semver200/version.h
  System/Semver200/version.inl
  System/meson.build
Labels: enhancement, refactor

#518 fix: add early return check when checking mods' `SupportedGameVersion`
  CHANGELOG.md
  Menus/MainMenuGUI.cpp
  RTEA.vcxproj
  RTEA.vcxproj.filters
  System/Constants.h
  System/DataModule.cpp
  System/DataModule.h
  System/GameVersion.h
  System/Reader.cpp
  System/Reader.h
  System/Semver200/Semver200_comparator.cpp
  System/Semver200/Semver200_modifier.cpp
  System/Semver200/Semver200_parser.cpp
  System/Semver200/semver200.h
  System/Semver200/version.h
  System/Semver200/version.inl
  System/meson.build
Labels: bug

#520 Pause Screen
  CHANGELOG.md
  Main.cpp
  Managers/ActivityMan.cpp
  Managers/ActivityMan.h
  Managers/ConsoleMan.cpp
  Managers/MenuMan.cpp
  Managers/MenuMan.h
  Managers/UInputMan.cpp
  Menus/LoadingScreen.cpp
  Menus/LoadingScreen.h
  Menus/ModManagerGUI.cpp
  Menus/ModManagerGUI.h
  Menus/PauseMenuGUI.cpp
  Menus/PauseMenuGUI.h
  Menus/SettingsGUI.cpp
  Menus/SettingsGUI.h
  Menus/SettingsVideoGUI.cpp
  Menus/TitleScreen.cpp
  Menus/TitleScreen.h
  Menus/meson.build
  RTEA.vcxproj
  RTEA.vcxproj.filters
Labels: enhancement
